Do not attempt to validate UID when none passed
Previously if no `--uid` option was passed at the command line, we would
still attempt to validate the passed UID and run the invalid IPA command
`ipa --uid=None` (plus some other args we always pass in
`ipa_utils.ipa_find`); this would then error with the message `ipa:
ERROR: invalid 'uid': must be an integer`.

Although we then swallowed this error and went on to handle this
correctly, running this unexpected IPA command was causing unit test
failures. We can both fix all the current unit test failures, and reduce
the risk of running this invalid IPA command causing future issues if
how we handle this later changes, by only attempting to validate the UID
when one has been passed.